### ISSUE TITLE
Adding a spatial sound to this effect?

### ISSUE THREAD

**Issue by DiegoVil** [rolandsmeenk/HololensScanningEffect#3]
Its not an issue, I would like to add some spatial sound to that effect? Where should I focus?

` private void SurfaceObserver_OnSurfaceChanged(SurfaceId id, SurfaceChange changeType, Bounds bounds, System.DateTime updateTime)`   `case SurfaceChange.Added:`

I would like to imitate a wave in the sea.

**Comment by rolandsmeenk** [comment]
You can place an audiosource at any position you like. Unity uses the HoloLens location to create spatialization of that audiosource. A wave maybe be implemented by a collection of audiosources that are positioned on a line.

**Comment by DiegoVil** [comment]
I would like to add sound not to a prerecorded room, I would like to do it with online spatial mappint. Maybe this is not the right place to ask it.

**Comment by rolandsmeenk** [comment]
You can dynamically create an AudioSource in a script and update it's position too. I don't believe there is built-in support for occlusion and reflections of audio although there exist a spatializer plugin that maybe of help. You could also perform a raycast against the spatialmapping geometry to implement some basic audio occlusion.
